### ISSUE TITLE
How to synchronize data to mongodb?

### ISSUE THREAD

**Issue by gglzf4** [Tandemly/eos-api-service#16]
Hi,how to synchronize data to mongodb?

**Comment by datchley** [comment]
Check out the README on the web wallet to see how to setup an eosd node as the connector. 

https://github.com/Tandemly/eos-web-wallet

That connector node's plugin setup for the mongodb host/port should match the one the api service is connecting to. That node will sync blocks/transactions/etc. to that mongodb used by the API service.

We'll update the docs on this repo on our next release to cover that here as well.

**Comment by gglzf4** [comment]
Because i had add db_plugin but not sync the chain data to mongodb,
I will try to add the db_plugin then run the eosd node again,
Thank you very much!
